---
# tasks file for win_service_config
- name: Install packages
  win_chocolatey:
    name: "{{ package_name }}"
    state: latest
    package_params: "{{ parameters}}"
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Restart a service
  win_service:
    name: "{{ service_name }}"
    state: started
    start_mode: auto
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Firewall rule to allow SSH  on TCP port 22
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
